import type { DistributionPhaseFormData } from "@/components/sections/distribution-phase-section"
import type { AgriculturalPhaseFormData } from "@components/sections/agricultural-phase-section"
import type { CompanyFormData } from "@components/sections/company-info-section"
import type { IndustrialPhaseFormData } from "@components/sections/industrial-phase-section"

export const COMPANY_INFO_INITIAL: CompanyFormData = {
  companyName: "",
  taxId: "",
  state: "",
  city: "",
  contactPerson: "",
  phone: "",
  email: "",
}

export const AGRICULTURAL_PHASE_INITIAL: AgriculturalPhaseFormData = {
  biomassType: "",
  hasConsumptionInfo: "",
  biomassInputSpecific: "",
  biomassImpactFactor: "",
  biomassCalorificValue: "",
  cornStarchInput: "",
  cornStarchConsumptionFactor: "",
  cornStarchImpact: "",
  biomassProductionImpact: "",
  biomassProductionState: "",
  cultivationType: "",
  woodResidueLifecycleStage: "",
  mutImpactFactor: "",
  mutAllocationPercent: "",
  mutImpactResult: "",
  transportDistanceKm: "",
  transportVehicleType: "",
  averageBiomassPerVehicleTon: "",
  transportDemandTkm: "",
  transportImpactResult: "",
}

export const INDUSTRIAL_PHASE_INITIAL = {
  hasCogeneration: "",
  processedBiomassKgPerYear: "",
  biomassConsumedInCogenerationKgPerYear: "",
  gridMixMediumVoltage: "",
  gridMixHighVoltage: "",
  electricityPCH: "",
  electricityBiomass: "",
  electricityDiesel: "",
  electricitySolar: "",
  electricityImpactFactorKgCO2PerKWh: "",
  electricityImpactResultKgCO2PerMJ: "",
  fuelDieselLitersPerYear: "",
  fuelNaturalGasNm3PerYear: "",
  fuelLPGKgPerYear: "",
  fuelGasolineALitersPerYear: "",
  fuelEthanolAnhydrousLitersPerYear: "",
  fuelEthanolHydratedLitersPerYear: "",
  fuelWoodChipsKgPerYear: "",
  fuelFirewoodKgPerYear: "",
  fuelProductionImpactKgCO2PerYear: "",
  fuelStationaryCombustionImpactKgCO2PerYear: "",
  fuelConsumptionImpactKgCO2PerMJ: "",
  biomassCombustionEmissionFactorKgCO2PerKg: "",
  biomassCombustionImpactKgCO2PerYear: "",
  biomassCombustionImpactKgCO2PerMJ: "",
  waterLitersPerYear: "",
  lubricantOilKgPerYear: "",
  silicaSandKgPerYear: "",
  manufacturingImpactKgCO2eqPerYear: "",
  manufacturingImpactKgCO2eqPerMJ: "",
} satisfies IndustrialPhaseFormData

export const DISTRIBUTION_PHASE_INITIAL = {
  domesticBiomassQuantityTon: "",
  domesticTransportDistanceKm: "",
  domesticRailPercent: "0",
  domesticWaterwayPercent: "0",
  domesticRoadPercent: "100",
  domesticRoadVehicleType: "",
  domesticDistributionImpactKgCO2EqPerYear: "",
  domesticMjTransportedPerYear: "",
  domesticImpactKgCO2EqPerMjTransported: "",
  // Export
  exportBiomassQuantityTon: "",
  exportDistanceFactoryToNearestHydroPortKm: "",
  exportRailPercentToPort: "0",
  exportWaterwayPercentToPort: "0",
  exportRoadPercentToPort: "0",
  exportRoadVehicleTypeToPort: "",
  exportDistancePortToForeignMarketKm: "",
  exportDistributionImpactFactoryToPortKgCO2EqPerYear: "",
  exportDistributionImpactPortToMarketKgCO2EqPerYear: "",
  exportMjTransportedPerYear: "",
  exportImpactKgCO2EqPerMjTransported: "",
} satisfies DistributionPhaseFormData
